[package]
name = "shortest_path"
version = "0.1.0"
authors = ["Sergey Veselkov <veselkovsd@yandex.ru>"]

[dependencies]
conrod = { version = "0.61.1", features = ["glium", "winit"] }
serde = "1.0.79"
serde_derive = "1.0.79"
bincode = "1.0.1"
failure = "0.1.2"
